controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute
#product_show:
#    path:       /product/{id}
#    controller: 'App\Controller\ProductController::show'
#    # expressions can retrieve route parameter values using the "params" variable
#    condition:  "params['id'] < 1000"